export const ADD_ITEMS_TO_CART_START = "ADD_ITEMS_TO_CART_START";
export const ADD_ITEMS_TO_CART_SUCCES = "ADD_ITEMS_TO_CART_SUCCES";
export const ADD_ITEMS_TO_CART_ERROR = "ADD_ITEMS_TO_CART_ERROR";

export const GET_ITEMS_IN_CART_START = "GET_ITEMS_IN_CART_START";
export const GET_ITEMS_IN_CART_SUCCES = "GET_ITEMS_IN_CART_SUCCES";
export const GET_ITEMS_IN_CART_ERROR = "GET_ITEMS_IN_CART_ERROR";

export const DELETE_ITEM_START = 'DELETE_ITEM_START';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR';


