// / FIREBASE AUTH ACTIONS
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
// export const LOGIN_WITH_PROVIDER_FIREBASE = 'LOGIN_WITH_PROVIDER_FIREBASE';

export const RESET_PASSWORD_BY_EMAIL_START = 'RESET_PASSWORD_BY_EMAIL_START';
export const RESET_PASSWORD_BY_EMAIL_SUCCESS = 'RESET_PASSWORD_BY_EMAIL_SUCCESS';
export const RESET_PASSWORD_BY_EMAIL_ERROR = 'RESET_PASSWORD_BY_EMAIL_ERROR';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
// export const REGISTER_FIREBASE_USER = 'REGISTER_FIREBASE_USER';

export const FETCH_FIREBASE_USER = 'FETCH_FIREBASE_USER';
export const UPDATE_FIREBASE_USER = 'UPDATE_FIREBASE_USER';
export const CHANGE_FIREBASE_USER_PASSWORD = 'CHANGE_FIREBASE_USER_PASSWORD';
export const LOGOUT = 'LOGOUT';
export const CHECK_AUTH = 'CHECK_AUTH';

export const UPLOAD_AVATAR_START = 'UPLOAD_AVATAR_START';
export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS';
export const UPLOAD_AVATAR_ERROR = 'UPLOAD_AVATAR_ERROR';

export const UPDATE_USER_PHOTO_URL_SUCCESS = 'UPDATE_USER_PHOTO_URL_SUCCESS';
export const UPDATE_USER_PHOTO_URL_ERROR = 'UPDATE_USER_PHOTO_URL_ERROR';
export const VALIDATE_AVATAR = 'VALIDATE_AVATAR';

export const UPDATE_USER_DISPLAY_NAME_SUCCESS = 'UPDATE_USER_DISPLAY_NAME_SUCCESS';
export const UPDATE_USER_DISPLAY_NAME_ERROR = 'UPDATE_USER_DISPLAY_NAME_ERROR';
export const UPDATE_USER_EMAIL_SUCCESS = 'UPDATE_USER_EMAIL_SUCCESS';
export const UPDATE_USER_EMAIL_ERROR = 'UPDATE_USER_EMAIL_ERROR';

export const REQUEST_AUTH = 'REQUEST_AUTH';
export const REAUTH_SUCCESS = 'REAUTH_SUCCESS';
export const REAUTH_ERROR = 'REAUTH_ERROR';

export const SEND_CONFIRMATION_EMAIL_SUCCESS = 'SEND_CONFIRMATION_EMAIL_SUCCESS';
export const SEND_CONFIRMATION_EMAIL_ERROR = 'SEND_CONFIRMATION_EMAIL_ERROR';

export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR';